apiVersion: apps/v1
kind: Deployment
metadata:
  name: fare-predict-deployment
  labels:
    app: fare-predict
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fare-predict
  template:
    metadata:
      labels:
        app: fare-predict
    spec:
      containers:
      - name: fare-predict
        image: public.ecr.aws/w6b5n9p7/python-demo:latest
        ports:
        - containerPort: 5000

