apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: fare-predict
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fare-predict
  template:
    metadata:
      labels:
        app: fare-predict
    spec:
      containers:
      - name: fare-predict
        image: 094853031708.dkr.ecr.us-east-1.amazonaws.com/python-demo:latest
        ports:
        - containerPort: 5000
-----------

apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  selector:
    app: fare-predict
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000