version: 0.2


phases:
  install:
    runtime-versions:
      python: 3.10
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - docker --version
      - aws ecr-public get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin public.ecr.aws/w6b5n9p7
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - pip install --upgrade pip
      - docker build -t $IMAGE_REPO:latest .
      - docker tag $IMAGE_REPO:latest public.ecr.aws/w6b5n9p7/$IMAGE_REPO:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push public.ecr.aws/w6b5n9p7/$IMAGE_REPO:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"fare-predict","imageUri":"%s"}]' public.ecr.aws/w6b5n9p7/$IMAGE_REPO:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
  files:
    - '**/*'